name: aqylym
description: Aqylym
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.3 <4.0.0"

# * Application Packages and Libraries
# * Flutter Packages overrides for conflict resolution
dependency_overrides:
  intl: ^0.18.1

dependencies:
  animations: ^2.0.7
  audio_session: ^0.1.21
  audioplayers: ^6.1.0
  auto_scroll: ^0.2.0
  auto_size_text: ^3.0.0
  autoscale_tabbarview: ^1.0.2
  centrifuge: ^0.14.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.2
  cupertino_modal_sheet: null
  device_info_plus: ^11.2.0
  dio: ^5.1.1
  drift: ^2.5.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  file_picker: ^8.1.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  fluent_ui: ^4.5.0
  fluentui_system_icons: ^1.1.199
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_chat_core: ^0.0.4
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.2.1
  flutter_flavorizr: ^2.1.5
  flutter_gen: ^5.1.0+1
  flutter_launcher_icons: ^0.13.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_markdown: ^0.7.4+2
  flutter_multi_formatter: ^2.9.11
  flutter_native_splash: ^2.2.15
  flutter_neat_and_clean_calendar: ^0.4.1
  flutter_riverpod: ^2.1.1
  flutter_scroll_shadow: ^1.2.6
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.5
  flutter_switch: ^0.3.2
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  gauge_indicator: ^0.4.3
  get_it: ^7.2.0
  go_router: ^14.2.3

  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^0.8.7+4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.1.1
  intl: ^0.18.1
  intl_utils: ^2.8.1
  introduction_screen: ^3.1.4
  json_annotation: ^4.7.0
  jwt_decode: ^0.3.1
  l: ^4.0.2
  linear_progress_bar: ^1.1.3
  lite_rolling_switch: ^1.0.1
  logger: ^2.5.0
  mime: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.0.8
  percent_indicator: ^4.2.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  popover: ^0.3.1
  protobuf: ^2.1.0
  provider: ^6.1.2
  pulsator: ^1.0.0
  record: ^5.1.2
  responsive_framework: ^1.0.0
  rxdart: ^0.27.7
  sabowsla_core_platform_interface: ^0.0.6
  scroll_to_index: ^3.0.1
  sentry_flutter: ^8.9.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  showcaseview: ^2.0.0+1
  skeletonizer: ^1.4.2
  skeletons: ^0.0.3
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.0.0
  stack_trace: ^1.11.1
  table_calendar: ^3.0.9
  transformable_list_view: ^0.6.0
  transparent_image: ^2.0.1
  url_launcher: ^6.1.14
  uuid: ^4.5.1
  web_socket_channel: ^2.4.0
  ws: ^1.0.0

# * Packages that will not be in the release version of app
dev_dependencies:
  bloc_test: ^9.1.1

  # * Code Generators
  # Generating Files
  build_runner: ^2.4.6

  # * UI Testing
  # Preview for different devices
  device_preview: ^1.1.0
  # Generate Fake Data
  faker: ^2.0.0
  # Generating Asset Files
  flutter_gen_runner: ^5.1.0+1

  # * Linter and code organization
  # Linter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # Code Generation for Models and Union Types
  freezed: ^2.2.0
  # Injecting Dependencies
  injectable_generator: ^2.1.1
  # Generating Serialization of JSON
  json_serializable: ^6.5.4
  # Data Mocking
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/splash/
    - assets/images/
    - assets/images/intro1.jpg
    - assets/images/intro2.jpg
    - assets/images/intro3.jpg
    - assets/images/intro4.jpg
    - assets/images/game1.svg
    - assets/images/game2.svg
    - assets/images/game3.svg
    - assets/images/1.svg
    - assets/images/star.svg
    - assets/images/book1.svg
    - assets/images/book2.svg
    # - lib/.env

  fonts:
    - family: app_icons
      fonts:
        - asset: assets/icons/app_icons.ttf

    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/sf-ui-display-black.otf
          weight: 900
        - asset: assets/fonts/sf-ui-display-bold.otf
          weight: 700
        - asset: assets/fonts/sf-ui-display-heavy.otf
          weight: 800
        - asset: assets/fonts/sf-ui-display-light.otf
          weight: 300
        - asset: assets/fonts/sf-ui-display-medium.otf
          weight: 500
        - asset: assets/fonts/sf-ui-display-semibold.otf
          weight: 600
        - asset: assets/fonts/sf-ui-display-thin.otf
          weight: 200
        - asset: assets/fonts/sf-ui-display-ultralight.otf
          weight: 100
# * Localizations generating config
flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/intl
  output_dir: lib/src/core/localization/generated
  class_name: S # This is the default class name for the generated delegate
  main_locale: ru # Specify your main locale
  translate_var: loc # This matches your context.loc usage

# * Flutter Icon Generator Configurations
flutter_icons:
  image_path: "assets/icons/prod.png"
  # Android Icon
  android: true
  adaptive_icon_background: "#1E1E1E"
  # iOS Icon
  ios: true
  remove_alpha_ios: true

# * Flutter Splash Screen Generator Configurations
flutter_native_splash:
  android: true
  ios: true
  color: "FFFFFF"
  color_dark: "000000"
  image: assets/splash/light.png
  image_dark: assets/splash/dark.png
  fullscreen: true
  android_gravity: center
  android_12:
    image: assets/splash/light.png
    image_dark: assets/splash/dark.png
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"

# * Flutter Flavor Configurations
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
      customConfig:
        minSdkVersion: 24
    ios:
      buildSettings: {}
  flavors:
    dev:
      app:
        name: "Aqylym"
        version: "0.0.1"
        buildNumber: "1"
        icon: "assets/icons/dev.png"
      android:
        applicationId: "kz.aqylym.app"
        flavorName: "Dev"
      ios:
        bundleId: "kz.aqylym.app"

    staging:
      app:
        name: "Aqylym"
        version: "0.0.1"
        buildNumber: "1"
        icon: "assets/icons/stage.png"
      android:
        applicationId: "kz.aqylym.app"
        flavorName: "Staging"
      ios:
        bundleId: "kz.aqylym.app"

    prod:
      app:
        name: "Aqylym"
        version: "0.0.1"
        buildNumber: "1"
        icon: "assets/icons/prod.png"
      android:
        applicationId: "kz.aqylym.app"
        flavorName: "Prod"
      ios:
        bundleId: "kz.aqylym.app"
